### ISSUE TITLE
social media card: change from "America" to "North America & Latin America"

### ISSUE THREAD

**Issue by reshamas** [pymc-devs/pymc-data-umbrella#21]
Currently, as it is, the word "America" centers on the "USA", whether intentional or not.

Other options:  
- North America and Latin America ===> preferred
- North and South America
- The Americas

cc:  @mjhajharia @OriolAbril

**Comment by OriolAbril** [comment]
On which page is it? It will help make the edit faster

Thanks for catching it. In both Catalan and Spanish America refers unambiguously to the whole continent, and even when speaking English I can't bring myself to process the America=USA meaning used by people in USA. And I am consequently constantly confused the other way around, reading america and assuming it's about the whole continent only to realize a couple of paragraphs later after seeing it makes no sense unless America=USA.

**Comment by reshamas** [comment]
@OriolAbril 
It's on the social media card here:  https://twitter.com/pymc_devs/status/1487369782605217792

As long as folks in Latin America and Canada are not feeling excluded with "America", it's fine with me.

**Comment by OriolAbril** [comment]
Oh, I can't edit the cards.

> As long as folks in Latin America and Canada are not feeling excluded with "America", it's fine with me.

This I don't know. My guess is it will depend on how much media from usa they consume and their ability to switch continental paradigms when switching languages which is probably better than mine on average

**Comment by ericmjl** [comment]
ho ho ho, at least _this_ Canadian isn't bothered by "America", because 'Murica is what we use to refer to that 50-state gun-toting, healthcare-crippled 1st world anomaly that I currently live in right now XD. Well, at least MA has something good going for it lol.

Jokes aside, the two cards side-by-side make it pretty clear to individuals with basic education about the globe that these refer to continents, not countries. If we've reached a place where words can be interpreted out of context, then I surrender! 🏳

**Comment by mjhajharia** [comment]
@reshamas controversies aside, i agree that we should try to make things as inclusive as possible and be on the safe side, some people might not feel weird, but some might and this sprint is really focussed on inclusiveness so i've updated the card on the meetup event, the pymc tweet has already gone so we can let that be as it is.
